<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="micro_servo" params="parent prefix *origin">

  <!-- Physical Material Macros -->
  <material name="Red">
    <color rgba="1.0 0 0 1.0" />
  </material>
  <material name="Green">
    <color rgba="0 1.0 0 1.0" />
  </material>
  <material name="Blue">
    <color rgba="0 0 1.0 1" />
  </material>
  <material name="Black">
    <color rgba="0 0 0 1.0" />
  </material>

  <xacro:property name="servo_length" value="0.022" />
  <xacro:property name="servo_width" value="0.011" />
  <xacro:property name="servo_heigth" value="0.021" />
  <xacro:property name="support_radius" value="${servo_width/2}" />
  <xacro:property name="support_heigth" value="0.005" />
  <xacro:property name="rot_link_length" value="0.032" />
  <xacro:property name="rot_link_width" value="0.005" />
  <xacro:property name="rot_link_heigth" value="0.004" />

  <joint name="${prefix}base_joint" type="fixed">
    <xacro:insert_block name="origin" />
    <parent link="${parent}"/>
    <child link="${prefix}base_link" />
  </joint>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${servo_length} ${servo_width} ${servo_heigth}" />
      </geometry>
      <origin xyz="0 0 ${servo_heigth/2}" rpy="0 0 0" />
      <material name="Blue" />
    </visual>
    <collision>
      <geometry>
        <box size="${servo_length} ${servo_width} ${servo_heigth}" />
      </geometry>
      <origin xyz="0 0 ${servo_heigth/2}" rpy="0 0 0" />
      <material name="Blue" />
    </collision>
  </link>

  <link name="support_link">
    <visual>
      <origin xyz="0 0 ${support_heigth/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${support_radius}" length="${support_heigth}" />
      </geometry>
      <material name="Blue" />
    </visual>
    <collision>
      <origin xyz="0 0 ${support_heigth/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${support_radius}" length="${support_heigth}" />
      </geometry>
      <material name="Blue" />
    </collision>
  </link>
  <joint name="base_to_support" type="fixed">
    <parent link="base_link" />
    <child link="support_link" />
    <origin xyz="0.005 0 ${servo_heigth}" rpy="0 0 0" />
  </joint>

  <link name="rot_link">
    <visual>
      <origin xyz="0 0 ${rot_link_heigth/2}" rpy="0 0 0" />
      <geometry>
        <box size="${rot_link_length} ${rot_link_width} ${rot_link_heigth}" />
      </geometry>
      <material name="Red" />
    </visual>
    <collision>
      <origin xyz="0 0 ${rot_link_heigth/2}" rpy="0 0 0" />
      <geometry>
        <box size="${rot_link_length} ${rot_link_width} ${rot_link_heigth}" />
      </geometry>
      <material name="Red" />
    </collision>
  </link>
  <joint name="support_to_rot_link" type="revolute">
    <parent link="support_link" />
    <child link="rot_link" />
    <axis xyz="0 0 1"/>
    <origin xyz="0 0 ${rot_link_heigth}" rpy="0 0 0" />
    <limit lower="0" upper="0" effort="1000" velocity="100"/>
  </joint>

</xacro:macro>

</robot>